###
@host = http://10.43.30.95:4000

################ Authors ##############
###
POST {{host}}/authors
Content-Type: application/json

{
    "authorName": "auth10",
    "yearBorn": "1970",
    "yearDied": "2009"
}
###

###
GET {{host}}/authors
###

###
PUT {{host}}/authors/5
Content-Type: application/json

{
    "authorName": "auth101010",
    "yearBorn": "1971"
}
###

###
DELETE {{host}}/authors/1
###