###
@host = http://10.43.30.95:4000

################ customers ##############
###
POST {{host}}/customers
Content-Type: application/json

{
    "name": "cus20",
    "street": "Flanks",
    "city": "Flweda",
    "state": "Luren",
    "country": "Austria"
}
###
###
GET {{host}}/customers?country=Austria
###
###
PUT {{host}}/customers/4
Content-Type: application/json

{
    "street": "Yuda"
}
###
###
DELETE {{host}}/customers/4
###
